<?php
declare(strict_types=1);

/**
 * @implements hook_theme();
 */
function views_pdf_theme($existing, $type, $theme, $path) : array {
  \Drupal::moduleHandler()->loadInclude('views_pdf', 'inc', 'views_pdf.theme');
  $module_dir = \Drupal::service('extension.list.module')->getPath('views_pdf');

  return [
    'views_view_pdf_unformatted' => [
      'path' => $path,
      'includes' => [ $module_dir . '/views_pdf.theme.inc' ],
    ]
  ];
}
